import * as cdk from 'aws-cdk-lib';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as cloudfrontOrigins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import * as cognito from 'aws-cdk-lib/aws-cognito';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import * as path from 'path';
import { Construct } from 'constructs';

export interface WebPortalProps {
  userPool: cognito.UserPool;
  userPoolClient: cognito.UserPoolClient;
  api: apigateway.RestApi;
}

/**
 * WebPortal — S3 bucket, CloudFront distribution, and S3 deployments
 * for the HPC Self-Service Portal frontend and documentation.
 */
export class WebPortal extends Construct {
  /** S3 bucket for static web portal assets. */
  public readonly bucket: s3.Bucket;
  /** CloudFront distribution for the web portal. */
  public readonly distribution: cloudfront.Distribution;

  constructor(scope: Construct, id: string, props: WebPortalProps) {
    super(scope, id);

    this.bucket = new s3.Bucket(this, 'WebPortalBucket', {
      bucketName: `hpc-portal-${cdk.Aws.ACCOUNT_ID}-${cdk.Aws.REGION}`,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    this.distribution = new cloudfront.Distribution(this, 'WebPortalDistribution', {
      comment: 'HPC Self-Service Portal',
      defaultBehavior: {
        origin: cloudfrontOrigins.S3BucketOrigin.withOriginAccessControl(this.bucket),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
      },
      defaultRootObject: 'index.html',
      errorResponses: [
        {
          httpStatus: 403,
          responseHttpStatus: 200,
          responsePagePath: '/index.html',
          ttl: cdk.Duration.seconds(0),
        },
        {
          httpStatus: 404,
          responseHttpStatus: 200,
          responsePagePath: '/index.html',
          ttl: cdk.Duration.seconds(0),
        },
      ],
    });

    // Deploy frontend assets to S3 and invalidate CloudFront cache.
    // The static files (HTML, CSS, app JS) are bundled from the frontend/
    // directory. A generated config.js with real deployment values is added
    // as a second source so the portal works immediately without manual
    // configuration. Later sources overwrite earlier ones, so the generated
    // config replaces the placeholder shipped in the frontend/ directory.
    //
    // The docs/ prefix is excluded from pruning so that the separate
    // DocsDeployment (below) is not wiped out by the --delete flag.
    new s3deploy.BucketDeployment(this, 'WebPortalDeployment', {
      sources: [
        s3deploy.Source.asset(path.join(__dirname, '..', '..', 'frontend')),
        s3deploy.Source.data(
          'js/config.js',
          [
            '/**',
            ' * Configuration for the HPC Self-Service Portal.',
            ' * Auto-generated by CDK during deployment — do not edit manually.',
            ' */',
            'const CONFIG = {',
            `  cognitoUserPoolId: '${props.userPool.userPoolId}',`,
            `  cognitoClientId: '${props.userPoolClient.userPoolClientId}',`,
            `  cognitoRegion: '${cdk.Aws.REGION}',`,
            `  apiBaseUrl: '${props.api.url}',`,
            '  clusterPollIntervalMs: 5000,',
            '  projectPollIntervalMs: 5000,',
            '  clusterCreationTimeoutMs: 9000000,',
            '};',
          ].join('\n'),
        ),
      ],
      destinationBucket: this.bucket,
      distribution: this.distribution,
      distributionPaths: ['/*'],
      exclude: ['docs/*'],
    });

    // Deploy documentation to S3 under the docs/ prefix
    new s3deploy.BucketDeployment(this, 'DocsDeployment', {
      sources: [s3deploy.Source.asset(path.join(__dirname, '..', '..', 'docs'))],
      destinationBucket: this.bucket,
      destinationKeyPrefix: 'docs',
      distribution: this.distribution,
      distributionPaths: ['/docs/*'],
    });
  }
}
